test:
	python -m unittest -v problem001 \
	                      problem002 \
	                      problem003 \
	                      problem004 \
	                      problem005 \
	                      problem006
	cd utils;make test

clean:
	rm -rf *.pyc *~ __pycache__
	cd utils;make clean
